import type { Metadata } from "next";
import "./globals.css";
import ConditionalNavbar from "@/components/layout/ConditionalNavbar";
import ConditionalFooter from "@/components/layout/ConditionalFooter";
import ClientLayout from "./_client-layout/ClientLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-antikor antialiased">
        <ClientLayout>
          <ConditionalNavbar />
          <main>{children}</main>
          <ConditionalFooter />
        </ClientLayout>
      </body>
    </html>
  );
}
